name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # chạy mỗi ngày 00:00 UTC
  workflow_dispatch: # Cho phép chạy thủ công luôn

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: nguyenlongCS
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake.gif

      - uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
